/**
 * LNLamas API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export class Chapter {
  // tslint:disable-next-line:variable-name
  public _id?: string;
  public parentRef?: string;

  public firstPageUri?: string;

  public chapterRef?: string;

  public title?: string;

  public updated?: string;
}

export default Chapter;
