/**
 * LNLamas API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export class Page {
  // tslint:disable-next-line:variable-name
  public _id?: string;
  public parentRef?: string;

  public pageRef?: string;

  public pageUri?: string;

  public pageNo?: number;

  public imageUri?: string;

  public pageContent?: string;
}
export default Page;
