import { SeriesStatus } from "./SeriesStatus";

/**
 * LNLamas API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export class Series {
  // tslint:disable-next-line:variable-name
  public _id?: string;

  public title?: string;

  public description?: string;

  public titlesAlternative?: string[];

  public seriesPageUri?: string;

  public coverImageUri?: string;

  public author?: string;

  public updated?: string;

  public tags?: string[];

  public genres?: string[];

  public status?: string;
  
  public rating?: SeriesStatus;
}
export default Series;
